# Generated by Django 3.1.7 on 2021-03-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwordID', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=255)),
                ('publish_date', models.CharField(max_length=255)),
                ('like_count', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('birtdate', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('last_join', models.CharField(max_length=255)),
                ('about', models.CharField(max_length=255)),
                ('me_flow', models.CharField(max_length=255)),
                ('flow', models.CharField(max_length=255)),
            ],
        ),
    ]
